### ISSUE TITLE
Derivation of the Fisher-z independence test

### ISSUE THREAD

**Issue by verae98** [py-why/causal-learn#111]
Hi, I would like to understand where the derivation of the Fisher-z test comes from. I have tried to derive it from Wikipedia (https://en.wikipedia.org/wiki/Partial_correlation), since that source is the most elaborating. I think I understand everything, but I am not very sure about why the inverse of the matrix is used. Is there any documentation available to read into?

Kind regards,
Vera

**Comment by MarkDana** [comment]
Hi Vera! This might help: https://en.wikipedia.org/wiki/Partial_correlation#Using_matrix_inversion
