### ISSUE TITLE
Passing required domain knowledge using add_required_by_node

### ISSUE THREAD

**Issue by sirineBS** [py-why/causal-learn#116]
Hello, 
I'm new in causal discovery, and I'm not sure if it's an issue in the causal-learn package or if I'm using wrongly the add_required_by_node function. 
I first built a graph based on data (without any knowledge), let's call it G1. 
Then I wanted to add required edges based on domain expertise to create a new graphe G2.
The expected result : G2 will contain all directed edges defined by domain knowledge.
The observed result : G2 contains the directed edge (if the edge was already present in G1), otherwise the directed edge is not created.

--------------
Below the details : 

- data: 
- ![data_graph](https://github.com/py-why/causal-learn/assets/6229497/0be5addb-cc72-4710-a784-1435aa2d5f97)

- First I create a graph without any knowledge (G1), using this code : 

```
from causallearn.search.ConstraintBased.PC import pc
      data_np = data.to_numpy()
      cg = pc(data_np)
```

below the result : 
![G1](https://github.com/py-why/causal-learn/assets/6229497/251f840b-1165-4e8d-b72e-4d4e331cce9a)

- Second I wanted to add domain knowledge rule 
rules = [

        ("a", "b", "required"), #a->b
        ("c", "d", "required"), #c->d
        ("b", "c", "required"), #b->c
    ]
I used add_required_by_node and add_forbidden_by_node methods to add either required or forbidden edges and to create the graph G2, using this code: 

```
forbidden_edges = []
required_edges =  [(0, 1), (2, 3), (1, 2)] # {"a":0, "b":1, "c":2, "d":3}
data_np = data.to_numpy()
cg = pc(data_np)
nodes = cg.G.get_nodes()

bk = BackgroundKnowledge()
for (node_1_idx, node_2_idx) in forbidden_edges:
    bk.add_forbidden_by_node(nodes[node_1_idx], nodes[node_2_idx])

for (node_1_idx, node_2_idx) in required_edges:
    bk.add_required_by_node(nodes[node_1_idx], nodes[node_2_idx])

cg_with_knowledge = pc(data_np, background_knowledge=bk)
```
below the result : 
![G2](https://github.com/py-why/causal-learn/assets/6229497/3f39ca76-77d1-4735-bf09-5edc08251a86)

While I was expecting more something like this (results based on another package): 
![G3](https://github.com/py-why/causal-learn/assets/6229497/fea4e16a-e6da-4fcc-8655-12a84d5e781f)

**Comment by zhi-yi-huang** [comment]
Hi @sirineBS! When orienting based on background knowledge, the algorithm will only orient the undirected edges in the causal graph, but will not add additional edges to the causal graph. For example, it only orients `a-b` to `a->b` in G2, but not `b-c` and `c-d`. Because the undirected edges `b-c` and `c-d` were deleted by skeleton search in PC algorithm.

**Comment by sirineBS** [comment]
> Hi @sirineBS! When orienting based on background knowledge, the algorithm will only orient the undirected edges in the causal graph, but will not add additional edges to the causal graph. For example, it only orients `a-b` to `a->b` in G2, but not `b-c` and `c-d`. Because the undirected edges `b-c` and `c-d` were deleted by skeleton search in PC algorithm.

Hi @zhi-yi-huang , thank you very much for your answer ! Do you know if there is a way with causal-learn package to get the result I want ? (basically something that instead of applying search with PC then complete some edge directions with background knowledge, first create edges based on domain knowledge  then complete the process discovery with PC algo ).

**Comment by zhi-yi-huang** [comment]
Perhaps merge the causal edges based on domain knowledge to the result of the PC algorithm. But it may cause the causal graph to have loops. I'm not sure if this is theoretically feasible.
