### ISSUE TITLE
math domain error

### ISSUE THREAD

**Issue by asha24choudhary** [py-why/causal-learn#119]
I'm getting math domain error while computing fisherz conditional independence test. [Here ](https://github.com/py-why/causal-learn/blob/main/causallearn/utils/cit.py) is the link of the fisherz test that PC is using to dicover the causal graph. I know the reason for the error, it is because of the the algorithm is trying to compute sqrt of the negative value 
<img width="371" alt="image" src="https://github.com/py-why/causal-learn/assets/62930073/b7bc55a3-970b-491b-b67c-5a8348440074">. 

Could you please tell me how can I resolve this problem?

**Comment by kunwuz** [comment]
Thanks for reaching out. We believe this issue is related to #29. The reason seems to be the violation of the required assumption of the input data, although we are not totally sure yet. Specifically, the covariance matrix might be singular so it doesn't have a proper inverse.

**Comment by asha24choudhary** [comment]
I just added some noise to the y variable. I did not get any errors. Don't know what should I conclude from this?

**Comment by kunwuz** [comment]
Hi, thanks for checking this. I calculated the determinant of the correlation matrix you provided and the result was close to zero. There may be some issues regarding the singularity check, or the math domain error could be due to other reasons. Let us check on this.

**Comment by jdramsey** [comment]
Just a thought, here's the Wikipedia page for partial correlation that
spells out the assumptions etc.:

https://en.wikipedia.org/wiki/Partial_correlation

This is the "matrix inversion" method. Maybe an assumption is being
violated.

**Comment by kunwuz** [comment]
Yes, the covariance matrix is assumed to be positive semi-definite, so its inverse should also be positive semi-definite. That means that its diagonal elements should be non-negative. So I guess it's still related to the assumption of singularity. 

However, I'm still confused why the singularity check didn't catch it. Perhaps it is due to some strange value issues and we could (temporarily) fix it by taking the absolute value?

**Comment by asha24choudhary** [comment]
Thank you so much for the immediate help.
