### ISSUE TITLE
operands could not be broadcast together with shapes error with GES

### ISSUE THREAD

**Issue by gz475** [py-why/causal-learn#126]
when I run

from causallearn.search.ScoreBased.GES import ges
Record = ges(X, 'local_score_marginal_general')

I got /opt/anaconda3/envs/cl/lib/python3.7/site-packages/causallearn/score/LocalScoreFunction.py in local_score_marginal_general(Data, Xi, PAi, parameters)
    786             covfunc,
    787             PA,
--> 788             2 * np.sqrt(T) * eix * np.diag(np.sqrt(eig_Kx)) / np.sqrt(eig_Kx[0]),
    789         )
    790 

ValueError: operands could not be broadcast together with shapes (16419,10) (10,10) 

How can I rewrite this function to make it work?

**Comment by kunwuz** [comment]
Hi, I just tested and didn't get this error. Could you please let me know the shape of X?
