### ISSUE TITLE
Questions related to graph and adjacency matrix using PC & FCI

### ISSUE THREAD

**Issue by asha24choudhary** [py-why/causal-learn#132]
Thank you for this amazing repo. I had two questions.

1) Is there a possibility to compare the graphs provided by PC & FCI using the networkx library for instance using isomorphic method described [here](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.isomorphism.is_isomorphic.html#networkx.algorithms.isomorphism.is_isomorphic)? I was thinking if there was a way to export the graphs that is compatible with networkx library?

2) I saw that I can get the adjacency matrix in lingam, is there a possibility to get the same using PC/FCI?

**Comment by kunwuz** [comment]
Hi, thanks for your interest. It is possible to get the adjacency matrix for PC & FCI as mentioned in the [doc](https://causal-learn.readthedocs.io/en/latest/search_methods_index/Constraint-based%20causal%20discovery%20methods/PC.html) as follows:
![image](https://github.com/py-why/causal-learn/assets/29473070/2624d1d3-1c87-49ed-b02d-322716a7e7ed)

And for FCI (G.graph[i,j]):

![image](https://github.com/py-why/causal-learn/assets/29473070/54b42aa4-7d14-4f63-bfc3-39fba1261f31)

I don't think there is an existing function for the first point, but I believe transferring the graph class in causal-learn to networkx-like graphs using [pywhy-graph](https://www.pywhy.org/pywhy-graphs/dev/reference/export/index.html) might be promising.

**Comment by asha24choudhary** [comment]
Thank you, I found that the causal graph object returned by PC can be visualized by networkx as shown in [this](https://causal-learn.readthedocs.io/en/latest/search_methods_index/Constraint-based%20causal%20discovery%20methods/PC.html#) doc, however, when I try to do the same using the Graph G returned by FCI it is not possible as the graph class is different in this case. The object returned by PC is 'causallearn.graph.GraphClass.CausalGraph', however, in case of FCI as we get two outputs (graph & edges), the graph object returned by FCI is completely different and I cannot visualise it. I don't know which python script should I edit to define the 'G.to_nx_graph()' method that can be used for FCI. Thank you in advance!
