### ISSUE TITLE
How to plot GES Causal Paths

### ISSUE THREAD

**Issue by MattFill** [py-why/causal-learn#137]
I have been experimenting with the GES algorithm to estimate causal paths from cross-sectional data. The following code produces the graph attached. I am wondering how I can estimate the causal direction between nodes from GES and visualize this?

# Set up
from causallearn.search.ScoreBased.GES import ges

data = df_dx[['Bio','Psycho','Dx','NumberChronicPainTypes_T0']]

# default parameters
Record = ges(data)

# or customized parameters
scoring = 'local_score_BIC'
maxP = None  # maximum number of parents when searching the graph
parameters = None
Record = ges(data, scoring, maxP, parameters)

# Visualization using pydot
from causallearn.utils.GraphUtils import GraphUtils
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import io

pyd = GraphUtils.to_pydot(Record['G'],labels=['Bio','Psycho','Dx','NumberChronicPainTypes_T0'])
tmp_png = pyd.create_png(f="png")
fp = io.BytesIO(tmp_png)
img = mpimg.imread(fp, format='png')
plt.axis('off')
plt.imshow(img)
plt.show()

# or save the graph
pyd.write_png('simple_test.png')

![simple_test](https://github.com/py-why/causal-learn/assets/72527980/07c54ffd-77d7-4985-b2ce-2130a2c58210)

**Comment by kunwuz** [comment]
Hi, thanks for the question. The output of GES is a Markov Equivalence Class, which means that there may exist edges of which the directions cannot be determined by the algorithm. It seems that the algorithm cannot determine any direction for your data.

If you would like to get direction for every edge, perhaps you may consider functional-constraint-based methods, such as LiNGAM. A usage case of LiNGAM can be found in [this notebook](https://github.com/py-why/dowhy/blob/main/docs/source/example_notebooks/dowhy_causal_discovery_example.ipynb).

**Comment by kunwuz** [comment]
No, LiNGAM only returns a directed acyclic graph. A bidirectional path as you mentioned will introduce cycles. FCI permits bi-directional edges, which may be useful.

**Comment by MattFill** [comment]
> No, LiNGAM only returns a directed acyclic graph. A bidirectional path as you mentioned will introduce cycles. FCI permits bi-directional edges, which may be useful.

I see. It seems that the FCI algorithm can't determine any direction for my data. I suppose this is inherent in the structure of my data that I will need to investigate. Thank you for your help!

![image](https://github.com/py-why/causal-learn/assets/72527980/b5dee346-62fc-43f0-854a-fd564a047039)

**Comment by jdramsey** [comment]
Sorry to interject--do you know if your data is Gaussian, non-Gaussian, linear, nonlinear, etc.?

**Comment by MattFill** [comment]
Two of my variables are Gaussian (Bio and Psycho), numberofpaintypes is ordinal and Dx is binary. Why do you ask?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jdramsey** [comment]
I assume you're treating the discrete variables as continuous since I don't
think causal-learn has a mixed score or test yet. (We were supposed to do
that but I don't think it's happened yet.)

With two Gaussian variables and two categorical variables, there is
theoretically no way to determine the directions of edges in a CPDAG that
aren't already oriented in the CPDAG.

That's why I was wondering.

**Comment by kunwuz** [comment]
Yeah, it would be good to have a mixed score or test. I know that there is a team that is interested in contributing a test for mixed-type data. Perhaps the work will start soon :)

BTW, let me know if anyone would like to contribute more scores or tests for mixed cases (maybe degenerate Gaussian?). Right now the only solution in causal-learn might be approximation using Kernel-based methods with small kernel width.

**Comment by MattFill** [comment]
I see. Thank you for the insight.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
