### ISSUE TITLE
Invalid trend option for vector_ar fit() function

### ISSUE THREAD

**Issue by ishwargov** [py-why/causal-learn#147]
https://github.com/py-why/causal-learn/blob/0901441d4d376356400da7a3a0e4bc2f5ee392df/causallearn/search/FCMBased/lingam/var_lingam.py#L263C38-L263C38

Only valid options are `{“c”, “ct”, “ctt”, “n”}` , https://www.statsmodels.org/dev/generated/statsmodels.tsa.vector_ar.var_model.VAR.fit.html#statsmodels.tsa.vector_ar.var_model.VAR.fit

Please take a look into it.

**Comment by kunwuz** [comment]
Thanks so much, it has been updated. The reason is a previous update on statsmodel: https://github.com/statsmodels/statsmodels/pull/7593.
