### ISSUE TITLE
How to save and reload CausalGraph class?

### ISSUE THREAD

**Issue by WilliamsToTo** [py-why/causal-learn#150]
Hey, just wanna know how to save and reload the CausalGraph return by PC algorithm.

**Comment by kunwuz** [comment]
I don't think there is an existing function to save the CausalGraph object, but perhaps you could try to save the adjacency matrix of the graph (cg.G.graph), which is a numpy array so np.save( ) works.

**Comment by priamai** [comment]
What about using the pickle module, so you save a binary representation? I didn't test it but it should work.

**Comment by priamai** [comment]
@WilliamsToTo try this it works for me

![image](https://github.com/py-why/causal-learn/assets/57333254/ba83556d-75f5-4d3d-81ec-a267a9c8c98a)

**Comment by priamai** [comment]
```
from causallearn.search.ConstraintBased.PC import pc
import pickle
# default parameters
cg = pc(data)

print(len(cg.G.nodes))
with open('myG.pkl', 'wb') as f:
  pickle.dump(cg.G, f, pickle.HIGHEST_PROTOCOL)


with open('myG.pkl', 'rb') as f:
  myG = pickle.load(f)
  print(len(myG.nodes))
```

**Comment by WilliamsToTo** [comment]
@priamai Thanks a lot.
