### ISSUE TITLE
when will the Causal-Learn support causal evaluation

### ISSUE THREAD

**Issue by cyrilmyself** [py-why/causal-learn#157]
Currently，the Causal-Learn only support causal discovery；but in practice we also need to evaluate the effect of Treatment to obejct，so when will we support causal evaluation

**Comment by mmarkakis** [comment]
Perhaps [dowhy](https://github.com/py-why/dowhy) could come handy for that purpose instead?

**Comment by kunwuz** [comment]
[Here](https://github.com/py-why/dowhy/blob/main/docs/source/example_notebooks/dowhy_causal_discovery_example.ipynb) is an example of how to do effect estimation with dowhy based on results from causal-learn.
