### ISSUE TITLE
Reference PC stable

### ISSUE THREAD

**Issue by fileds** [py-why/causal-learn#158]
In the implementation of the PC algorithm with parameter stable=True, is the implementation based on Colombo and Maathuis, 2014, https://jmlr.csail.mit.edu/papers/v15/colombo14a.html ? In that case, consider adding reference to the docs about PC algorithm.

Colombo D, Maathuis MH (2014). "Order-Independent Constraint-Based Causal Structure Learning". Journal of Machine Learning Research, 15:3921–3962.

**Comment by kunwuz** [comment]
Thanks for the reminder! We have added the reference to the PC documentation.
