### ISSUE TITLE
Null Hypothesis in Conditoinal Independence Tests

### ISSUE THREAD

**Issue by arainboldt** [py-why/causal-learn#166]
Hi!

What's the null hypothesis in the conditional independence tests? Is it independence or dependence?

e.g. https://github.com/py-why/causal-learn/blob/main/causallearn/utils/cit.py#L294

I'm trying to understand exactly how to interpret the p-value returned from the CIT methods.

Thanks!

Andrew

**Comment by kunwuz** [comment]
Hi, I think the null hypothesis is conditional independence.

**Comment by arainboldt** [comment]
This was my assumption. I just wanted to confirm. Thanks.

**Comment by jdramsey** [comment]
Sorry I was up all night working on another project; let me get my head in
this space again. I'll get back to you in an hour or so. My sense (I need
to build the example in the Tetrad interface again to confirm) is that you
succeeded with the Tetrad FCI to make sure variables were not associated in
either tier. If the collider hadn't been oriented, then the first and third
variable in the second tier would have been associated.

Maybe if you tell me what you're trying to accomplish in the bigger picture
I can give advice that's more satisfying to you, haha :-D

**Comment by jdramsey** [comment]
Oh I'm sorry sorry, I'm responding to multiple people in my email and this
is irrelevant to your discussion. Please ignore!
