### ISSUE TITLE
Key error FCI

### ISSUE THREAD

**Issue by nlagrang** [py-why/causal-learn#187]
Hi,

thanks for this super useful package ! 👍  

When I run the following command  : 

`g, edges = fci(matrix.to_numpy(),independence_test_method="gsq",verbose=False,alpha=0.05)`

I get the following error : 

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[16], line 1
----> 1 g, edges = fci(matrix.to_numpy(),independence_test_method="gsq",verbose=False,alpha=0.05)
      2 matrix_pag = g.graph
      3 pag = np.zeros((len(matrix_pag),len(matrix_pag)))

File ~\anaconda3\lib\site-packages\causallearn\search\ConstraintBased\FCI.py:775, in fci(dataset, independence_test_method, alpha, depth, max_path_length, verbose, background_knowledge, show_progress, **kwargs)
    773 change_flag = False
    774 change_flag = rulesR1R2cycle(graph, background_knowledge, change_flag, verbose)
--> 775 change_flag = ruleR3(graph, sep_sets, background_knowledge, change_flag, verbose)
    777 if change_flag or (first_time and background_knowledge is not None and
    778                    len(background_knowledge.forbidden_rules_specs) > 0 and
    779                    len(background_knowledge.required_rules_specs) > 0 and
    780                    len(background_knowledge.tier_map.keys()) > 0):
    781     change_flag = ruleR4B(graph, max_path_length, dataset, independence_test_method, alpha, sep_sets,
    782                           change_flag,
    783                           background_knowledge, verbose)

File ~\anaconda3\lib\site-packages\causallearn\search\ConstraintBased\FCI.py:351, in ruleR3(graph, sep_sets, bk, changeFlag, verbose)
    348 if (not graph.is_adjacent_to(node_A, node_D)) or (not graph.is_adjacent_to(node_C, node_D)):
    349     continue
--> 351 if not isNoncollider(graph, sep_sets, node_A, node_D, node_C):
    352     continue
    354 if graph.get_endpoint(node_A, node_D) != Endpoint.CIRCLE:

File ~\anaconda3\lib\site-packages\causallearn\search\ConstraintBased\FCI.py:323, in isNoncollider(graph, sep_sets, node_i, node_j, node_k)
    321 def isNoncollider(graph: Graph, sep_sets: Dict[Tuple[int, int], Set[int]], node_i: Node, node_j: Node,
    322                   node_k: Node) -> bool:
--> 323     sep_set = sep_sets[(graph.get_node_map()[node_i], graph.get_node_map()[node_k])]
    324     return sep_set is not None and sep_set.__contains__(graph.get_node_map()[node_j])

KeyError: (2, 4) 

[input.csv](https://github.com/user-attachments/files/16245710/input.csv)

I've attached the input file. If I change the alpha to 0.051 it works, for example

Thanks

**Comment by zhi-yi-huang** [comment]
Thank you for your feedback. I tried to run the data you gave using the code from the main branch, and I didn't find the problem you mentioned. What version of causal-learn are you using? Or you can try using the latest version of causal-learn.

**Comment by nlagrang** [comment]
Thanks for your feedback and help ! I've installed the latest version available on Github and I no longer get this error message ;)
