### ISSUE TITLE
Using scoring function 'local_score_marginal_multi' on ges() function gives error

### ISSUE THREAD

**Issue by vera98x** [py-why/causal-learn#91]
When I call the ges() function with the score function [local_score_marginal_multi](https://causal-learn.readthedocs.io/en/latest/score_functions_index/gml.html#generalized-score-with-marginal-likelihood) with no parameters, it gives the following error: ```File "lib\site-packages\causallearn\score\LocalScoreFunction.py", line 824, in local_score_marginal_multi
    X = Data[:, parameters["dlabel"][Xi]]
KeyError: 0``` 

It looks like the labels of the parameters are not correctly parsed. In the LocalScoreFunction.py ```Xi``` is an int, but the parameters["dlabel"] have that the keys are strings. However, fixing this problem locally gives other errors, so I am not sure what goes wrong further.

The same applies when using the function with the score function```local_score_CV_multi```

**Comment by kunwuz** [comment]
Hi, I'm not sure that I clearly understand the question. Does it work if trying something like: `Record = ges(X, 'local_score_marginal_general')`

**Comment by vera98x** [comment]
Thank you for your response, the 'local_score_marginal_general' does work, so then probably I am not have the correct data format as input then for the 'local_score_marginal_multi' score function?

**Comment by kunwuz** [comment]
Thanks so much for your feedback. We will look into it and let you know the solution as soon as possible.

**Comment by kunwuz** [comment]
Hi, if you would like to, could you please try the newest version on GitHub to see if there are any issues remaining?

**Comment by kunwuz** [comment]
It's also on PyPI now, so please feel free to give it a try via pip.
