### ISSUE TITLE
Question: Clarification on Edge properties from FCI algo

### ISSUE THREAD

**Issue by arainboldt** [py-why/causal-learn#98]
In the [docs](https://causal-learn.readthedocs.io/en/latest/search_methods_index/Constraint-based%20causal%20discovery%20methods/FCI.html) the edge properties are explained as:

"""
edges: list. Contains graph’s edges properties. If edge.properties have the Property ‘dd’, then there is no latent confounder. Otherwise, there might be latent confounders. If edge.properties have the Property ‘nl’, then it is definitely direct. Otherwise, it is possibly direct.
"""
The abbreviations seem odd to me. Unfortunately, I can't find the original paper on the internet free and I can't find another reference to these abbreviations. Consequently, I'm inquiring here for clarification.

Is it possible that `dd` and `nl` have been switched? I.e. `dd` means `definitely direct` and `nl` means `no latent`?

Additionally, there is no explanation fro `pl`. Does it mean `possible latent confounders`?

I'm guessing that `pd` means `possibly direct`.

Thanks for the clarification!

**Comment by jdramsey** [comment]
These are from Tetrad PAG "graph coloring" and are as follows.

"nl" means "no latent"--i.e., this is a visible edge.
"pl" means "possibly latent"--i.e., this is not a visible edge.
"dd" means "definitely direct"--i.e., one can expect this edge to actually exist as a direct edge in the true DAG (with latents)
"pd" means "possibly direct"--i.e., this may go through other variables in the underlying DAG (with latents), like X->L->Y where L is latent.

**Comment by jdramsey** [comment]
I checked with Peter about the definition of "possibly direct"; the above is correct sfaik.

**Comment by kunwuz** [comment]
Thanks so much! This issue has just been solved in this [PR ](https://github.com/py-why/causal-learn/pull/99)by @zhi-yi-huang. Please let us know if there are any further questions.

**Comment by arainboldt** [comment]
Thanks a lot to both of you!
